<a href="https://colab.research.google.com/github/utkarshub543/python-Fundamentals/blob/main/Numpy_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
print(type)

<class 'type'>


### **Using Built-in Functions:**

In [ ]:
zeros_arr = np.zeros((3, 3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_arr = np.ones((2, 2))
print(ones_arr)

[[1. 1.]
 [1. 1.]]


In [ ]:
lin_arr = np.linspace(0, 1, 5)
print(lin_arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [ ]:
  rand_arr = np.random.rand(3, 3)
  print(rand_arr)

[[0.77343995 0.50391279 0.5193949 ]
 [0.16708896 0.63163008 0.68545148]
 [0.59797912 0.12919503 0.39060845]]


In [ ]:
arr = np.array([1,2,3,4], ndmin=25)
print(arr)


[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]]]]]


In [ ]:
print(arr.reshape((2,2)))

[[1 2]
 [3 4]]


In [ ]:
print(arr.shape)

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [ ]:
print(arr.shape)

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


### ***Data Type Codes:***

i – integer, b – Boolean, u – unsigned integer, f – float, c – complex float, m – timedelta, M – datetime, O – object, S – string, U – unicode string, V – fixed chunk of memory for other type ( void )

In [ ]:
arr = np.array([1,2,3,4])

print(arr.dtype)

int64


In [ ]:
arr = np.array([1,1.5,2,2.5,3,4,5,6,7,8,8.5,9,9.5])

print(arr.dtype)

float64


In [ ]:
arr = np.array(['dogs','cats','horses'], dtype='U')

print(arr.dtype)


<U6


In [ ]:
import numpy as nparr

In [ ]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
w = np.array[1,3]
print(w)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
element = np.array[0, 1]
print(element)

TypeError: 'builtin_function_or_method' object is not subscriptable

### **Create the following rank 2 array with shape (3, 4)**

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### ***Slicing***

In [ ]:
w = a[1, :]
print(w)

[5 6 7 8]


In [ ]:
slice_column = a[:, 2]
print(slice_column)

[ 3  7 11]


## **Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2; b is the following array of shape (2, 2):**

In [ ]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


### ***Print 77***

In [ ]:
print(a[0, 1])

77


### **b[0, 0] is the same piece of data as a[0, 1]**

In [ ]:
b[0, 0] = 77
print(b)

[[77  3]
 [ 6  7]]


In [ ]:
print(a[0, 1])

77


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [ ]:
addition = arr1 + arr2

substraction = arr1-arr2

multiplication = arr1 * arr2

division = arr1 / arr2

print(addition)
print(substraction)
print(multiplication)
print(division)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
np.arange(10) + np.arange(10)

In [ ]:
np.linspace(0, 1, 5)